### ISSUE TITLE
What is the run ?

### ISSUE THREAD

**Issue by soufiane8096** [philipperemy/Leboncoin#1]
Hi, 

I cloned your project, and I tried to run it in Eclipse. I've launched the run.main but I got several errors :  log/leboncoin.log (No such file or directory)
	at java.io.FileOutputStream.open(Native Method)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:142)
	at java.io.FileWriter.<init>(FileWriter.java:78)
	at log.Printer.<init>(Printer.java:18)
	at log.Logger.<clinit>(Logger.java:11)
	at mail.MailManager.doActionGmail(MailManager.java:58)
	at mail.MailManager.doAction(MailManager.java:20)
	at run.DeleteAdMailCleaner.run(DeleteAdMailCleaner.java:11)
	at run.main.App.start(App.java:21)
	at run.main.App.main(App.java:15)
Exception in thread "main" java.lang.NullPointerException
	at log.Printer.println(Printer.java:29)22/05/2017 19:47:09 [ERROR] [MailManager] A1 BAD Invalid SASL argument. b20mb278242306wmb

	at log.Logger.traceERROR(Logger.java:89)
	at mail.MailManager.doActionGmail(MailManager.java:58)
	at mail.MailManager.doAction(MailManager.java:20)
	at run.DeleteAdMailCleaner.run(DeleteAdMailCleaner.java:11)
	at run.main.App.start(App.java:21)
	at run.main.App.main(App.java:15)

Can you describe how to launch it ? and how to use it please ?

Thank you

**Comment by philipperemy** [comment]
I'll have to dig into the code again! It's been a long time.

In that case it's because you need to create a folder called `log` at the root of the project.
